SELECT * FROM produtos LIMIT 5;
SELECT * FROM clientes LIMIT 3;
SELECT * from produtos WHERE nome='Televisão 43"';
INSERT INTO produtos (nome, preco) VALUES ('Macbook Pro 13"',1700000);
DELETE FROM clientes WHERE nome='Orlando Pequeno Jesus';
UPDATE produtos SET preco=8000 WHERE nome='Pelúcia Strange Planet com Gatinho';
UPDATE produtos SET preco=980000 WHERE nome='Violão Lava ME 2';
UPDATE clientes SET cpf='04652651298' WHERE nome='Luccas Santarém Branco';
INSERT INTO compras (id_cliente, id_produto) VALUES ((SELECT id FROM clientes WHERE nome = 'Chico Buarque de Holanda'), (SELECT id FROM produtos WHERE nome = 'Violão Lava ME 2'));
INSERT INTO compras (id_cliente, id_produto) VALUES ((SELECT id FROM clientes WHERE nome = 'Olga Cascais Fortunato'), (SELECT id FROM produtos WHERE nome = 'Celular Topo de Linha'));
DELETE FROM compras WHERE id_cliente = (SELECT id FROM clientes WHERE nome = 'Martinha Lima Zambujal') AND id_produto = (SELECT id FROM produtos WHERE nome = 'Fone Topo de Linha');
SELECT * FROM produtos ORDER BY preco ASC;
SELECT * FROM produtos ORDER BY preco ASC LIMIT 3;
SELECT * FROM produtos ORDER BY preco DESC LIMIT 1;
SELECT * FROM produtos ORDER BY preco ASC LIMIT 1 OFFSET 1;
SELECT * FROM produtos WHERE nome LIKE '%Televisão%';
SELECT * FROM produtos WHERE preco<100000;
SELECT * FROM produtos WHERE preco<200000 AND nome LIKE '%Celular%';
SELECT * FROM clientes WHERE id NOT IN (SELECT id_cliente FROM compras);
SELECT * FROM produtos WHERE id IN (SELECT id_produto FROM compras WHERE id_cliente IN (SELECT id FROM clientes WHERE nome='Benício Freire Sampaio'));